---

- name: perform nim check
  hosts: all 
  gather_facts: no

  collections:
    - ibm.power_aix

  tasks:
    - name: nim check
      nim:
        action: 'check'
      register: nim_output
    - debug: var=nim_output
